
#
# Notice: Any links, references, or attachments that contain sample scripts, code, or commands comes with the following notification.
#
# This Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment.
# THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# We grant You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form of the Sample Code,
# provided that You agree:
#
# (i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded;
# (ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; and
# (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits,
# including attorneys’ fees, that arise or result from the use or distribution of the Sample Code.
#
# Please note: None of the conditions outlined in the disclaimer above will superseded the terms and conditions contained within the Premier Customer Services Description.
#
# DEMO POC - "AS IS"

on:
  workflow_call:
    inputs:
      resourceGroupName:
        required: true
        type: string
      location:
        required: true
        type: string
      environmentName:
        required: true
        type: string
    secrets:
      azure_credentials:
        required: true
      subscriptionId:
        required: true     
    outputs:
      formRecognizerName:
        description: 'The name of the form recognizer'
        value: ${{ jobs.create-azure-resources.outputs.formRecognizerName }}
      storageName:
        description: 'The name of the storage'
        value: ${{ jobs.create-azure-resources.outputs.storageName }}        

jobs:
  create-azure-resources:
    
    runs-on: ubuntu-latest

    outputs:
      formRecognizerName: ${{ steps.armDeployment.outputs.formRecognizerName }}
      storageName: ${{ steps.armDeployment.outputs.storageName }}

    steps:


      - uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
         if: runner.os == 'Linux'

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}  

      - name: Create Resource Group
        run: |
          az group create -n ${{ inputs.resourceGroupName }} -l ${{ inputs.location }}

      # Temporary step the bicep linter return an error today for the
      # method PATCH for CORS on storage
      - name: Convert to ARM template
        run: |
          bicep build ./bicep/main.bicep
          
          
      - name: Deploy Azure Resources
        id: armDeployment
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.subscriptionId }}
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: ./bicep/main.json
          parameters: environmentName=${{ inputs.environmentName }}

      - name: logout
        run: |
          az logout
